### ISSUE TITLE
Cannot access /home/xxx/.config/bamboohr/google-calendar.json

### ISSUE THREAD

**Issue by scherler** [agentgonzo/bamboohr-google-calendar-sync#2]
```
/usr/lib/python2.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/thorsten/.config/bamboohr/google-calendar.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "bamboohr-google-calendar-sync.py", line 82, in <module>
    app = CalendarSync()
  File "bamboohr-google-calendar-sync.py", line 38, in __init__
    self.gcal_client = GoogleCalendar(config[Config.GCAL_SECTION]['calendar_id'])
  File "/home/thorsten/src/mysterion/bamboohr-google-calendar-sync/google_calendar_client.py", line 42, in __init__
    flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
  File "/usr/lib/python2.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/usr/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/usr/lib/python2.7/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'google-calendar-client-secret.json', 'No such file or directory', 2)
```

**Comment by jcarsique** [comment]
Same issue, regardless the target account (personal or professional).
